format: diffusers
pipeline: z_image
transformer_additional_kwargs:
    control_layers_places: [0, 10, 20]
    control_refiner_layers_places: [0, 1]
    add_control_noise_refiner: true
    add_control_noise_refiner_correctly: true
    control_in_dim: 33